"use client";
import {Suspense,useEffect,useRef,useState} from "react"; import {useSearchParams} from "next/navigation";
function VoiceTraining(){const q=useSearchParams();const preset=q.get("scenarioId");const [scenarios,setScenarios]=useState<any[]>([]),[scenarioId,setScenarioId]=useState(preset||""),[messages,setMessages]=useState<any[]>([]),[listening,setListening]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState("");const rec=useRef<any>(null);
useEffect(()=>{fetch("/api/scenarios").then(r=>r.json()).then(d=>{const a=d.scenarios||[];setScenarios(a);if(!scenarioId&&a[0])setScenarioId(a[0].id)})},[]);
const speak=(text:string)=>{if(typeof window==="undefined"||!("speechSynthesis"in window))return;window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang="ru-RU";u.rate=.95;window.speechSynthesis.speak(u)};
const send=async(text:string)=>{if(!text.trim()||busy)return;const next=[...messages,{role:"manager",content:text}];setMessages(next);setBusy(true);try{const r=await fetch("/api/training/realtime",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({scenarioId,history:next})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Ошибка AI");setMessages([...next,{role:"client",content:d.reply}]);speak(d.reply)}catch(e:any){setError(e.message)}finally{setBusy(false)}};
const startListening=()=>{const SR=(window as any).SpeechRecognition||(window as any).webkitSpeechRecognition;if(!SR){setError("Голосовой ввод не поддерживается этим браузером.");return}const r=new SR();r.lang="ru-RU";r.interimResults=false;r.continuous=false;r.onstart=()=>{setListening(true);setStarted(Date.now())};r.onend=async()=>{setListening(false);const duration=started?Date.now()-started:0;const r=await fetch("/api/training/voice/metrics",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({transcript,durationMs:duration})});const d=await r.json();if(d.metrics)setMetrics(d)};r.onerror=()=>setError("Не удалось распознать речь.");r.onresult=(e:any)=>{const text=e.results[0][0].transcript;setTranscript(t=>(t+" "+text).trim());send(text);};rec.current=r;r.start()};
return <div><div className="pageHead"><div><p className="eyebrow">VOICE AI</p><h1>Голосовая тренировка</h1><p className="muted">Говори с AI-клиентом вслух. Ответ клиента будет озвучен автоматически.</p></div><span className="liveBadge">● VOICE</span></div><div className="card voicePicker"><label>Сценарий<select value={scenarioId} onChange={e=>setScenarioId(e.target.value)}>{scenarios.map(x=><option key={x.id} value={x.id}>{x.title}</option>)}</select></label></div>{error&&<p className="errorText">{error}</p>}<div className="card voiceChat"><div className="voiceMessages">{messages.map((m,i)=><div className={"bubble "+m.role} key={i}><small>{m.role==="manager"?"Ты":"AI-клиент"}</small>{m.content}</div>)}{!messages.length&&<div className="chatEmpty"><div className="voiceOrb">◉</div><h2>Нажми и говори</h2><p className="muted">AI будет отвечать голосом.</p></div>}</div><div className="voiceControls"><button className={"voiceButton "+(listening?"listening":"")} onClick={startListening} disabled={listening||busy||!scenarioId}>{listening?"Слушаю…":"🎙 Говорить"}</button><button className="ghost" onClick={()=>{setMessages([]);window.speechSynthesis?.cancel()}}>Сбросить</button></div>{metrics&&<div className="voiceFeedback"><b>Анализ речи</b><span>Темп: {metrics.feedback?.pace}</span><span>Слова: {metrics.metrics?.words}</span><span>Заполнители: {metrics.metrics?.fillerCount}</span><span>Паузы: {metrics.metrics?.pauseCount}</span></div>}</div></div>}

export default function VoiceTrainingPage(){return <Suspense fallback={<div className="card"><h2>Загрузка…</h2></div>}><VoiceTraining/></Suspense>}
